spring.application.name=mesa-livre-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mesa_livre
spring.datasource.username=postgres
spring.datasource.password=685103

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080